// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2627A1JCKCwKuisdyE_Z42R9VepyUXaI',
    appId: '1:536635798176:web:3e65fe04a0a2adbe09cfc5',
    messagingSenderId: '536635798176',
    projectId: 'automate-61876',
    authDomain: 'automate-61876.firebaseapp.com',
    storageBucket: 'automate-61876.firebasestorage.app',
    measurementId: 'G-5NLHN0JY8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDFhhTX0uOxIAfaojJKuUFoGX1fevMGRg',
    appId: '1:536635798176:android:124325040d22a84109cfc5',
    messagingSenderId: '536635798176',
    projectId: 'automate-61876',
    storageBucket: 'automate-61876.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_TtLkIAFjk8xq-UrgpsFa8TZsdD3kkas',
    appId: '1:536635798176:ios:de59eedcf9d1a92309cfc5',
    messagingSenderId: '536635798176',
    projectId: 'automate-61876',
    storageBucket: 'automate-61876.firebasestorage.app',
    iosBundleId: 'com.example.automate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_TtLkIAFjk8xq-UrgpsFa8TZsdD3kkas',
    appId: '1:536635798176:ios:de59eedcf9d1a92309cfc5',
    messagingSenderId: '536635798176',
    projectId: 'automate-61876',
    storageBucket: 'automate-61876.firebasestorage.app',
    iosBundleId: 'com.example.automate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2627A1JCKCwKuisdyE_Z42R9VepyUXaI',
    appId: '1:536635798176:web:9c5a0b5a8c4a8c2509cfc5',
    messagingSenderId: '536635798176',
    projectId: 'automate-61876',
    authDomain: 'automate-61876.firebaseapp.com',
    storageBucket: 'automate-61876.firebasestorage.app',
    measurementId: 'G-XJC6032V6R',
  );
}
