import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart'; // Import shared_preferences
import '../models/reminder.dart';
import '../models/vehicle.dart'; // Needed for vehicle selection
import '../providers/auth_provider.dart';
import '../services/reminder_service.dart';
import '../services/vehicle_service.dart'; // Needed to fetch vehicles
import '../services/notification_service.dart'; // Import NotificationService

class AddReminderScreen extends StatefulWidget {
  const AddReminderScreen({super.key});

  @override
  State<AddReminderScreen> createState() => _AddReminderScreenState();
}

class _AddReminderScreenState extends State<AddReminderScreen> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _titleController = TextEditingController();
  final TextEditingController _notesController = TextEditingController();
  DateTime? _selectedDueDate;
  Vehicle? _selectedVehicle;
  Future<List<Vehicle>>? _vehiclesFuture;

  @override
  void initState() {
    super.initState();
    _vehiclesFuture = _fetchVehicles();
  }

  Future<List<Vehicle>> _fetchVehicles() async {
    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final token = await authProvider.user?.getIdToken();
    if (token == null) {
      throw Exception('Not authenticated');
    }
    return VehicleService.getVehicles(token);
  }

  Future<void> _selectDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _selectedDueDate ?? DateTime.now(),
      firstDate: DateTime.now(),
      lastDate: DateTime(2101),
    );
    if (picked != null && picked != _selectedDueDate) {
      setState(() {
        _selectedDueDate = picked;
      });
    }
  }

  Future<void> _submitForm() async {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();

      if (_selectedDueDate == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Por favor, selecciona una fecha de vencimiento.')),
        );
        return;
      }

      try {
        final authProvider = Provider.of<AuthProvider>(context, listen: false);
        final token = await authProvider.user?.getIdToken();
        if (token == null) throw Exception('Not authenticated');

        final newReminderData = Reminder(
          id: '', // ID will be generated by the backend
          userId: authProvider.user!.uid, // Firebase UID
          vehicleId: _selectedVehicle?.id,
          title: _titleController.text,
          notes: _notesController.text.isEmpty ? null : _notesController.text,
          dueDate: _selectedDueDate!,
          createdAt: DateTime.now(),
        );

        final createdReminder = await ReminderService.createReminder(token, newReminderData);

        // Schedule notification if enabled
        final prefs = await SharedPreferences.getInstance();
        final notificationsEnabled = prefs.getBool('notificationsEnabled') ?? false;
        if (notificationsEnabled && createdReminder.id != null) {
          NotificationService().scheduleNotification(createdReminder, 7, createdReminder.id.hashCode + 7);
        }

        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Recordatorio creado con éxito!')),
        );
        context.pop(true); // Pop with true to indicate success and refresh previous screen
      } catch (e) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error al crear recordatorio: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Añadir Recordatorio'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              TextFormField(
                controller: _titleController,
                decoration: const InputDecoration(
                  labelText: 'Título',
                  border: OutlineInputBorder(),
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Por favor, introduce un título.';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _notesController,
                decoration: const InputDecoration(
                  labelText: 'Notas (Opcional)',
                  border: OutlineInputBorder(),
                ),
                maxLines: 3,
              ),
              const SizedBox(height: 16),
              ListTile(
                title: Text(
                  _selectedDueDate == null
                      ? 'Seleccionar Fecha de Vencimiento'
                      : 'Fecha de Vencimiento: ${_selectedDueDate!.toLocal().toString().split(' ')[0]}',
                ),
                trailing: const Icon(Icons.calendar_today),
                onTap: () => _selectDate(context),
              ),
              const SizedBox(height: 16),
              FutureBuilder<List<Vehicle>>(
                future: _vehiclesFuture,
                builder: (context, snapshot) {
                  if (snapshot.connectionState == ConnectionState.waiting) {
                    return const Center(child: CircularProgressIndicator());
                  }
                  if (snapshot.hasError) {
                    return Text('Error al cargar vehículos: ${snapshot.error}');
                  }
                  if (!snapshot.hasData || snapshot.data!.isEmpty) {
                    return const Text('No hay vehículos disponibles para asignar.');
                  }

                  final vehicles = snapshot.data!;
                  return DropdownButtonFormField<Vehicle>(
                    decoration: const InputDecoration(
                      labelText: 'Vehículo (Opcional)',
                      border: OutlineInputBorder(),
                    ),
                    value: _selectedVehicle,
                    onChanged: (Vehicle? newValue) {
                      setState(() {
                        _selectedVehicle = newValue;
                      });
                    },
                    items: vehicles.map<DropdownMenuItem<Vehicle>>((Vehicle vehicle) {
                      return DropdownMenuItem<Vehicle>(
                        value: vehicle,
                        child: Text(vehicle.nickname ?? '${vehicle.make} ${vehicle.model}'),
                      );
                    }).toList(),
                  );
                },
              ),
              const SizedBox(height: 24),
              ElevatedButton(
                onPressed: _submitForm,
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 12),
                  textStyle: const TextStyle(fontSize: 18),
                ),
                child: const Text('Crear Recordatorio'),
              ),
            ],
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    _titleController.dispose();
    _notesController.dispose();
    super.dispose();
  }
}